---
# This playbook contains plays to install and maintain cjdns.

- name: install cjdns makedepends packages
  pacman: name={{ item }} state=installed
  with_items:
    - cmake
    - git

- name: create cjdns build directory
  file: state=directory path={{ cjdns_build_dir }}
    owner=root group=users mode=0775

- name: create cjdns pkgbuild file
  copy: src=PKGBUILD dest={{ cjdns_build_dir }}/PKGBUILD
    owner=root group=users mode=0664

- name: create update-cjdns script
  template: src=update-cjdns.j2 dest=/usr/local/bin/update-cjdns
    owner=root group=root mode=0755

- name: configure the cjdns daemon
  copy: src="{{ ansible_fqdn }}-cjdroute.conf" dest=/etc/cjdroute.conf
    owner=root group=root mode=0644
  notify: restart the cjdns daemon

- name: build and install cjdns from git
  command: /usr/local/bin/update-cjdns

- name: start the cjdns daemon and enable on boot
  service: name=cjdns state=started enabled=true
