---
# This playbook contains plays to install and maintain cjdns.

- name: install cjdns makedepends packages
  pacman: name={{ item }} state=installed
  with_items:
    - cmake
    - git
  tags: maintenance

- name: create cjdns build directory
  file: state=directory path={{ cjdns_build_dir }}
    owner=root group=users mode=0775
  tags: maintenance

- name: create cjdns pkgbuild file
  copy: src=PKGBUILD dest={{ cjdns_build_dir }}/PKGBUILD
    owner=root group=users mode=0664
  tags: maintenance

- name: create update-cjdns script
  template: src=update-cjdns.j2 dest=/usr/local/bin/update-cjdns
    owner=root group=root mode=0755
  tags: maintenance

#- include: users.yml tags=users
