---
# This playbook configures vnStat for network traffic monitoring.

- name: install the vnstat package
  pacman: name=vnstat state=installed

- name: start the vnstat daemon and enable it on boot
  service: name=vnstat state=started enabled=true
